
/**
 *
 * @author imed
 */
module ServerCenterApp
{
  interface ServerCenterIDL
  {
      string createMRecord(in string methodName, in string manager_ID,in string  firstName, in string lastName, in long employeeID, in string mailID, in string projectID, in  string clientName, in string projectName, in string location); 
	   
   // signature of second remote method
   
   
   
	 string getRecordCounts(in string methodName, in string Manager_ID);
	
	 string createERecord(in string methodName, in string Manager_ID,in string firstName,in string lastName,in long employeeID,in string mailID,in string projectID); 
			
	 string transferRecord(in string methodName, in string Manager_ID, in string recordID, in string remoteCenterServer);
	
	 string editRecord(in string methodName, in string Manager_ID,in string recordID, in string fieldName, in string newValue);
	
	 
	

	 
    



	oneway void shutdown();
    };
};