package ServerCenterApp;


/**
* ServerCenterApp/ServerCenterIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerCenterIDL.idl
* Tuesday, November 13, 2018 6:20:20 o'clock PM EST
*/

public interface ServerCenterIDL extends ServerCenterIDLOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerCenterIDL
