package ServerCenterApp;


/**
* ServerCenterApp/ServerCenterIDLOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerCenterIDL.idl
* Tuesday, November 13, 2018 6:20:20 o'clock PM EST
*/

public interface ServerCenterIDLOperations 
{
  String createMRecord (String methodName, String manager_ID, String firstName, String lastName, int employeeID, String mailID, String projectID, String clientName, String projectName, String location);

  // signature of second remote method
  String getRecordCounts (String methodName, String Manager_ID);
  String createERecord (String methodName, String Manager_ID, String firstName, String lastName, int employeeID, String mailID, String projectID);
  String transferRecord (String methodName, String Manager_ID, String recordID, String remoteCenterServer);
  String editRecord (String methodName, String Manager_ID, String recordID, String fieldName, String newValue);
  void shutdown ();
} // interface ServerCenterIDLOperations
