package ServerCenterApp;

/**
* ServerCenterApp/ServerCenterIDLHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerCenterIDL.idl
* Tuesday, November 13, 2018 6:20:20 o'clock PM EST
*/

public final class ServerCenterIDLHolder implements org.omg.CORBA.portable.Streamable
{
  public ServerCenterApp.ServerCenterIDL value = null;

  public ServerCenterIDLHolder ()
  {
  }

  public ServerCenterIDLHolder (ServerCenterApp.ServerCenterIDL initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServerCenterApp.ServerCenterIDLHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServerCenterApp.ServerCenterIDLHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServerCenterApp.ServerCenterIDLHelper.type ();
  }

}
