package ServerCenterApp;


/**
* ServerCenterApp/ServerCenterIDLHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerCenterIDL.idl
* Tuesday, November 13, 2018 6:20:20 o'clock PM EST
*/

abstract public class ServerCenterIDLHelper
{
  private static String  _id = "IDL:ServerCenterApp/ServerCenterIDL:1.0";

  public static void insert (org.omg.CORBA.Any a, ServerCenterApp.ServerCenterIDL that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ServerCenterApp.ServerCenterIDL extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ServerCenterApp.ServerCenterIDLHelper.id (), "ServerCenterIDL");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ServerCenterApp.ServerCenterIDL read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServerCenterIDLStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ServerCenterApp.ServerCenterIDL value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ServerCenterApp.ServerCenterIDL narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServerCenterApp.ServerCenterIDL)
      return (ServerCenterApp.ServerCenterIDL)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ServerCenterApp._ServerCenterIDLStub stub = new ServerCenterApp._ServerCenterIDLStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ServerCenterApp.ServerCenterIDL unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServerCenterApp.ServerCenterIDL)
      return (ServerCenterApp.ServerCenterIDL)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ServerCenterApp._ServerCenterIDLStub stub = new ServerCenterApp._ServerCenterIDLStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
